//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolManagment.DataLayer.DatabaseModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Day
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Day()
        {
            this.TimeInDayAlternates = new HashSet<TimeInDayAlternate>();
        }
    
        public int DayId { get; set; }
        public int FkCalenderId { get; set; }
        public byte FkTypeDayId { get; set; }
        public byte FkDayAlternate { get; set; }
    
        public virtual Calender Calender { get; set; }
        public virtual DayAlternate DayAlternate { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TimeInDayAlternate> TimeInDayAlternates { get; set; }
        public virtual TypeDay TypeDay { get; set; }
    }
}
