//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolManagment.DataLayer.DatabaseModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class FieldsOfNewYearInUnGradute
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public FieldsOfNewYearInUnGradute()
        {
            this.LessonsOfFileldsOfNewYearInUngrades = new HashSet<LessonsOfFileldsOfNewYearInUngrade>();
        }
    
        public int PkFieldsOfNewYearInUnGradutesId { get; set; }
        public int FkFieldId { get; set; }
        public int FkUnGradutesInNewYearId { get; set; }
    
        public virtual Field Field { get; set; }
        public virtual UnderGradutesInNewAcademyYear UnderGradutesInNewAcademyYear { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LessonsOfFileldsOfNewYearInUngrade> LessonsOfFileldsOfNewYearInUngrades { get; set; }
    }
}
