//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolManagment.DataLayer.DatabaseModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class LessonsOfFileldsOfNewYearInUngrade
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public LessonsOfFileldsOfNewYearInUngrade()
        {
            this.TeacherTeachsLessonsOfNewYearInUnGrades = new HashSet<TeacherTeachsLessonsOfNewYearInUnGrade>();
        }
    
        public int PkLessonOfFieldOfNewYearInUnGradeId { get; set; }
        public int FkFieldOfNewYearInUnGraduteId { get; set; }
        public int FkLessonId { get; set; }
    
        public virtual FieldsOfNewYearInUnGradute FieldsOfNewYearInUnGradute { get; set; }
        public virtual Lesson Lesson { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TeacherTeachsLessonsOfNewYearInUnGrade> TeacherTeachsLessonsOfNewYearInUnGrades { get; set; }
    }
}
