//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolManagment.DataLayer.DatabaseModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class PersonalRole
    {
        public int PKPersonalRoles { get; set; }
        public int FkPersonId { get; set; }
        public int FkRoleId { get; set; }
    
        public virtual Personal Personal { get; set; }
        public virtual Role Role { get; set; }
    }
}
