//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolManagment.DataLayer.DatabaseModel
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SchoolManagmentEntities : DbContext
    {
        public SchoolManagmentEntities()
            : base("name=SchoolManagmentEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AcademyYear> AcademyYears { get; set; }
        public virtual DbSet<Calender> Calenders { get; set; }
        public virtual DbSet<Class> Classes { get; set; }
        public virtual DbSet<DayAlternate> DayAlternates { get; set; }
        public virtual DbSet<Day> Days { get; set; }
        public virtual DbSet<Field> Fields { get; set; }
        public virtual DbSet<FieldsOfNewYearInUnGradute> FieldsOfNewYearInUnGradutes { get; set; }
        public virtual DbSet<Grade> Grades { get; set; }
        public virtual DbSet<Lesson> Lessons { get; set; }
        public virtual DbSet<LessonsOfFileldsOfNewYearInUngrade> LessonsOfFileldsOfNewYearInUngrades { get; set; }
        public virtual DbSet<Permission> Permissions { get; set; }
        public virtual DbSet<Personal> Personals { get; set; }
        public virtual DbSet<Role> Roles { get; set; }
        public virtual DbSet<ScoreOfStudentsForLesson> ScoreOfStudentsForLessons { get; set; }
        public virtual DbSet<StudentMustPresentinClassesWhicTeacherTeachLessonAccToCalenderInClass> StudentMustPresentinClassesWhicTeacherTeachLessonAccToCalenderInClasses { get; set; }
        public virtual DbSet<Student> Students { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<Teacher> Teachers { get; set; }
        public virtual DbSet<TeacherTeachLessonAccordingToCalender> TeacherTeachLessonAccordingToCalenders { get; set; }
        public virtual DbSet<TeacherTeachLessonAccToCalenderInClass> TeacherTeachLessonAccToCalenderInClasses { get; set; }
        public virtual DbSet<TeacherTeachsLessonsOfNewYearInUnGrade> TeacherTeachsLessonsOfNewYearInUnGrades { get; set; }
        public virtual DbSet<TimeAlterNate> TimeAlterNates { get; set; }
        public virtual DbSet<TypeDay> TypeDays { get; set; }
        public virtual DbSet<UnderGradute> UnderGradutes { get; set; }
        public virtual DbSet<UnderGradutesInNewAcademyYear> UnderGradutesInNewAcademyYears { get; set; }
    }
}
