//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolManagment.DataLayer.DatabaseModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudentPresent
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public StudentPresent()
        {
            this.StudenPresentDetails = new HashSet<StudenPresentDetail>();
        }
    
        public int PkStudentPresents { get; set; }
        public int FkStudentMustPresentinClassesWhicTeacherTeachLessonAccToCalenderInClassId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StudenPresentDetail> StudenPresentDetails { get; set; }
        public virtual StudentMustPresentinClassesWhicTeacherTeachLessonAccToCalenderInClass StudentMustPresentinClassesWhicTeacherTeachLessonAccToCalenderInClass { get; set; }
    }
}
