//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolManagment.DataLayer.DatabaseModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Student
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Student()
        {
            this.ScoreOfStudentsForLessons = new HashSet<ScoreOfStudentsForLesson>();
            this.StudentMustPresentinClassesWhicTeacherTeachLessonAccToCalenderInClasses = new HashSet<StudentMustPresentinClassesWhicTeacherTeachLessonAccToCalenderInClass>();
        }
    
        public int StudentId { get; set; }
        public int FkStudentFieldId { get; set; }
        public Nullable<int> FkLastPassedUgraduteId { get; set; }
        public string StudentNationCode { get; set; }
        public string StudentName { get; set; }
    
        public virtual Field Field { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ScoreOfStudentsForLesson> ScoreOfStudentsForLessons { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StudentMustPresentinClassesWhicTeacherTeachLessonAccToCalenderInClass> StudentMustPresentinClassesWhicTeacherTeachLessonAccToCalenderInClasses { get; set; }
        public virtual UnderGradute UnderGradute { get; set; }
    }
}
