//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolManagment.DataLayer.DatabaseModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudentMustPresentinClassesWhicTeacherTeachLessonAccToCalenderInClass
    {
        public int PkStudentMustPresentinClassesWhicTeacherTeachLessonAccToCalenderInClassId { get; set; }
        public int FkStudentId { get; set; }
        public int FkTeacherTeachLessonAccToCalenderInClass { get; set; }
        public Nullable<System.DateTime> DateOfDay { get; set; }
        public bool StudentPresent { get; set; }
    
        public virtual Student Student { get; set; }
        public virtual TeacherTeachLessonAccToCalenderInClass TeacherTeachLessonAccToCalenderInClass { get; set; }
    }
}
