//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolManagment.DataLayer.DatabaseModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudentMustPresentinClassesWhicTeacherTeachLessonAccToCalenderInClass
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public StudentMustPresentinClassesWhicTeacherTeachLessonAccToCalenderInClass()
        {
            this.ScoreOfStudentsForLessons = new HashSet<ScoreOfStudentsForLesson>();
            this.StudentPresents = new HashSet<StudentPresent>();
        }
    
        public int PkStudentMustPresentinClassesWhicTeacherTeachLessonAccToCalenderInClassId { get; set; }
        public int FkStudentId { get; set; }
        public int FkTeacherTeachLessonAccToCalenderInClass { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ScoreOfStudentsForLesson> ScoreOfStudentsForLessons { get; set; }
        public virtual Student Student { get; set; }
        public virtual TeacherTeachLessonAccToCalenderInClass TeacherTeachLessonAccToCalenderInClass { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StudentPresent> StudentPresents { get; set; }
    }
}
