//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolManagment.DataLayer.DatabaseModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudentPresent
    {
        public int PkStudentPresents { get; set; }
        public int FkStudentMustPresentinClassesWhicTeacherTeachLessonAccToCalenderInClassId { get; set; }
        public Nullable<bool> StudentIsPresent { get; set; }
        public System.DateTime DateOfDay { get; set; }
    
        public virtual StudentMustPresentinClassesWhicTeacherTeachLessonAccToCalenderInClass StudentMustPresentinClassesWhicTeacherTeachLessonAccToCalenderInClass { get; set; }
    }
}
