//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolManagment.DataLayer.DatabaseModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class TeacherTeachsLessonsOfNewYearInUnGrade
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TeacherTeachsLessonsOfNewYearInUnGrade()
        {
            this.ScoreOfStudentsForLessons = new HashSet<ScoreOfStudentsForLesson>();
            this.TeacherTeachLessonAccordingToCalenders = new HashSet<TeacherTeachLessonAccordingToCalender>();
        }
    
        public int TeacherTeachLessonId { get; set; }
        public int FkTeacherId { get; set; }
        public int FkLessonOfFieldsOfNewYearInUnGrade { get; set; }
    
        public virtual LessonsOfFileldsOfNewYearInUngrade LessonsOfFileldsOfNewYearInUngrade { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ScoreOfStudentsForLesson> ScoreOfStudentsForLessons { get; set; }
        public virtual Teacher Teacher { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TeacherTeachLessonAccordingToCalender> TeacherTeachLessonAccordingToCalenders { get; set; }
    }
}
