//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolManagment.DataLayer.DatabaseModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class TeacherTeachLessonAccordingToCalender
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TeacherTeachLessonAccordingToCalender()
        {
            this.TeacherTeachLessonAccToCalenderInClasses = new HashSet<TeacherTeachLessonAccToCalenderInClass>();
        }
    
        public int PKTeacherTeachLessonAccordingToCalender { get; set; }
        public int FKTeacherTeachLessonId { get; set; }
        public int FkCalenderId { get; set; }
    
        public virtual Calender Calender { get; set; }
        public virtual TeacherTeachsLessonsOfNewYearInUnGrade TeacherTeachsLessonsOfNewYearInUnGrade { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TeacherTeachLessonAccToCalenderInClass> TeacherTeachLessonAccToCalenderInClasses { get; set; }
    }
}
