//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolManagment.DataLayer.DatabaseModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class TimeInDayAlternate
    {
        public int PKTimeInDayAlternate { get; set; }
        public int FkDayId { get; set; }
        public byte FkTimeAlternate { get; set; }
    
        public virtual Day Day { get; set; }
        public virtual TimeAlterNate TimeAlterNate { get; set; }
    }
}
