//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolManagment.DataLayer.DatabaseModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class UnderGradute
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public UnderGradute()
        {
            this.Fields = new HashSet<Field>();
            this.Students = new HashSet<Student>();
            this.UnderGradutes1 = new HashSet<UnderGradute>();
            this.UnderGradutesInNewAcademyYears = new HashSet<UnderGradutesInNewAcademyYear>();
        }
    
        public int PkUnGraduteId { get; set; }
        public Nullable<int> FkUnGradutePrequestis { get; set; }
        public int FkGradeId { get; set; }
        public string UnGraduteName { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Field> Fields { get; set; }
        public virtual Grade Grade { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Student> Students { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UnderGradute> UnderGradutes1 { get; set; }
        public virtual UnderGradute UnderGradute1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UnderGradutesInNewAcademyYear> UnderGradutesInNewAcademyYears { get; set; }
    }
}
