//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolManagment.DataLayer.DatabaseModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class UnderGradutesInNewAcademyYear
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public UnderGradutesInNewAcademyYear()
        {
            this.FieldsOfNewYearInUnGradutes = new HashSet<FieldsOfNewYearInUnGradute>();
        }
    
        public int PkUnderGraduteInAcademyYearId { get; set; }
        public int FkAcademyYearId { get; set; }
        public int FkUnGraduteId { get; set; }
    
        public virtual AcademyYear AcademyYear { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FieldsOfNewYearInUnGradute> FieldsOfNewYearInUnGradutes { get; set; }
        public virtual UnderGradute UnderGradute { get; set; }
    }
}
